import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Green Light Sporting Consult",
  description: "Generated by harnicode",
  icons: {
    icon: "/logo.ico" // Add favicon path here
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/logo.ico" />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
